[workspace]
resolver = "2"
members = ["crates/*"]
exclude = ["crates/xpath-fpc"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"

[workspace.dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
thiserror = "2"
mlua = { version = "0.12", features = ["lua54", "vendored"] }
assert_cmd = "2"
predicates = "3"
tempfile = "3"

[workspace.lints.clippy]
unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
todo = "warn"
unimplemented = "warn"
