[package]
name = "fmd-lua"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
fmd-http = { path = "../fmd-http" }
mlua.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
serde_json = "1"
tempfile.workspace = true
tracing-subscriber = { workspace = true, features = ["json"] }
