[package]
name = "fmd-lua"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
fmd-http = { path = "../fmd-http" }
log = "0.4"
mlua.workspace = true
rquickjs = "0.14"
thiserror.workspace = true

[dev-dependencies]
fmd-testkit = { path = "../fmd-testkit" }
tempfile.workspace = true
